#!/bin/bash

namespace="$1"
secretName="$2"
key="$3"
value="$4"

bash -c "kubectl get secret $secretName -n $namespace -o json | jq --arg $key "$(echo -n $value | base64)" '.data[\"$key\"]=\$$key' | kubectl apply -f -"
