#!/bin/bash

namespace="$1"
secretName="$2"
key="$3"


kubectl get secrets $secretName -n $namespace --template={{.data.$key}} | base64 -d 2>/dev/null

if [ $? -eq 65 ]; then
  echo "Key $key not found"
fi
